name: Deploy to Cloudflare Workers

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  deploy:
    name: Deploy MCP Server
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'pnpm'

      - name: Setup pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 8

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Build project
        run: pnpm run build

      - name: Deploy to Cloudflare Workers
        uses: cloudflare/wrangler-action@v3
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          command: deploy
          workingDirectory: .

  test:
    name: Test Deployment
    runs-on: ubuntu-latest
    needs: deploy
    if: success()
    
    steps:
      - name: Test health endpoint
        run: |
          # Wait a moment for deployment to be ready
          sleep 10
          
          # Test health endpoint
          curl -f https://nimiq-mcp-server.${{ secrets.CLOUDFLARE_ACCOUNT_ID }}.workers.dev/health || exit 1
          
          # Test info endpoint
          curl -f https://nimiq-mcp-server.${{ secrets.CLOUDFLARE_ACCOUNT_ID }}.workers.dev/info || exit 1