name: Preview Deployment

on:
  pull_request:
    types: [opened, synchronize, reopened]
    branches:
      - main

jobs:
  preview:
    name: Deploy Preview
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Set up pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 10

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Build project
        run: pnpm run build

      - name: Deploy preview to Cloudflare Workers
        id: deploy
        env:
          CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          CLOUDFLARE_ACCOUNT_ID: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
        run: |
          WORKER_NAME="nimiq-mcp-pr-${{ github.event.pull_request.number }}"
          pnpm exec wrangler deploy --name "$WORKER_NAME" --compatibility-date 2025-09-01
          echo "worker_name=$WORKER_NAME" >> $GITHUB_OUTPUT

      - name: Comment preview URL on PR
        uses: actions/github-script@v7
        with:
          script: |
            const prNumber = context.issue.number;
            const workerName = '${{ steps.deploy.outputs.worker_name }}';
            const previewUrl = `https://${workerName}.je-cf9.workers.dev`;

            const comment = `## 🚀 Preview Deployment Ready!

            Your preview deployment is now available:
            - **Base URL**: ${previewUrl}
            - **MCP Endpoint**: ${previewUrl}/mcp
            - **Health Check**: ${previewUrl}/health
            - **Info**: ${previewUrl}/info
            - **Web Interface**: ${previewUrl}/

            ### OpenAI Agents SDK Configuration

            **Python:**
            \`\`\`python
            from openai import OpenAI
            from mcp import MCPServerStreamableHttp

            nimiq_mcp = MCPServerStreamableHttp(
                name="Nimiq MCP Preview",
                params={
                    "url": "${previewUrl}/mcp",
                    "timeout": 30
                }
            )
            \`\`\`

            **TypeScript:**
            \`\`\`typescript
            {
              type: "mcp",
              server_label: "nimiq-preview",
              server_url: "${previewUrl}/mcp"
            }
            \`\`\`

            The preview will update automatically with new commits.`;

            // Check if comment already exists
            const { data: comments } = await github.rest.issues.listComments({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: prNumber
            });

            const existingComment = comments.find(c =>
              c.user.login === 'github-actions[bot]' &&
              c.body.includes('Preview Deployment Ready')
            );

            if (existingComment) {
              await github.rest.issues.updateComment({
                owner: context.repo.owner,
                repo: context.repo.repo,
                comment_id: existingComment.id,
                body: comment
              });
            } else {
              await github.rest.issues.createComment({
                owner: context.repo.owner,
                repo: context.repo.repo,
                issue_number: prNumber,
                body: comment
              });
            }

      - name: Test preview health endpoint
        run: |
          sleep 10
          WORKER_NAME="${{ steps.deploy.outputs.worker_name }}"
          curl -f "https://${WORKER_NAME}.je-cf9.workers.dev/health" || exit 1
