name: Preview Deployment

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  preview:
    name: Deploy Preview
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Set up pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 10

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Build project
        run: pnpm run build

      - name: Deploy preview to Cloudflare Workers
        id: deploy
        uses: cloudflare/wrangler-action@v3
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          command: deploy --env preview-pr-${{ github.event.pull_request.number }}
          workingDirectory: .

      - name: Comment preview URL on PR
        uses: actions/github-script@v7
        with:
          script: |
            const prNumber = context.issue.number;
            const previewUrl = `https://preview-pr-${prNumber}.nimiq-mcp.je-cf9.workers.dev`;

            const comment = `## 🚀 Preview Deployment Ready!

            Your preview deployment is now available:
            - **SSE Endpoint**: ${previewUrl}/sse
            - **Health Check**: ${previewUrl}/health
            - **Info**: ${previewUrl}/info
            - **Web Interface**: ${previewUrl}/

            ### OpenAI Agents SDK Configuration
            \`\`\`python
            MCPServerStreamableHttp(
                name="Nimiq MCP Preview",
                params={
                    "url": "${previewUrl}/sse",
                    "timeout": 10
                }
            )
            \`\`\`

            The preview will update automatically with new commits.`;

            github.rest.issues.createComment({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: prNumber,
              body: comment
            });

      - name: Test preview health endpoint
        run: |
          sleep 10
          curl -f https://preview-pr-${{ github.event.pull_request.number }}.nimiq-mcp.je-cf9.workers.dev/health || exit 1
